# canal.instance.mysql.slaveId=0
canal.instance.gtidon=false

# ??????? Docker ???? mysql ??
canal.instance.master.address=mysql:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

canal.instance.tsdb.enable=true
canal.instance.dbUsername=canal
canal.instance.dbPassword=Canal@123456
canal.instance.connectionCharset=UTF-8
canal.instance.enableDruid=false

# ???????
canal.instance.filter.regex=ruiwen\\.outbox
canal.instance.filter.black.regex=mysql\\.slave_.*

canal.mq.topic=example
canal.mq.partition=0
canal.instance.multi.stream.on=false