version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ruiwen-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ruiwen
      TZ: UTC
    command:
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --server-id=1
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - ruiwen-net

  redis:
    image: redis:7.2-alpine
    container_name: ruiwen-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass 1234
    volumes:
      - ./redis/data:/data
    networks:
      - ruiwen-net

  kafka:
    image: apache/kafka:3.7.0
    container_name: ruiwen-kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # 绑定三个通道：EXTERNAL给外部(公网)，INTERNAL给内部(Docker)，CONTROLLER给集群管理
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      # 【核心修复】对外宣称的地址：公网来的走你的IP，Docker内部来的走kafka服务名
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://103.236.80.221:9092,INTERNAL://kafka:29092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # 配置通道映射
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      CLUSTER_ID: 4L62no9pSFm676Y8v_A9LA
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    networks:
      - ruiwen-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
    container_name: ruiwen-es
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9201:9200"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins/ik:/usr/share/elasticsearch/plugins/ik
    networks:
      - ruiwen-net

  canal:
    image: canal/canal-server:v1.1.7
    container_name: ruiwen-canal
    platform: linux/amd64
    restart: always
    ports:
      - "11111:11111"
    environment:
      - CANAL_DESTINATIONS=example
    volumes:
      - ./canal/logs:/home/admin/canal-server/logs
      - ./canal/conf/example/instance.properties:/home/admin/canal-server/conf/example/instance.properties
    networks:
      - ruiwen-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ruiwen-kafka-ui
    restart: always
    ports:
      - "18080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=ruiwen-cluster
      # 这里直接使用你网络内部的 kafka 容器名和端口
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - ruiwen-net

networks:
  ruiwen-net:
    driver: bridge

